---
name: Molecule test
on:
  push:
    paths:
      - defaults/**
      - handlers/**
      - meta/**
      - molecule/**
      - tasks/**
      - templates/**
      - vars/**
      - .github/**

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos7
          - centos6
          - ubuntu1804
          - debian9
          - debian10
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.3
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
        with:
          image: ubuntu
